shl_catalogue = [
    {
        "name": "Software Engineering Assessment",
        "url": "https://shl.com/assessments/software-engineering-assessment",
        "remote_support": True,
        "adaptive": True,
        "duration": "60 mins",
        "test_type": "Skill-based",
        "roles": ["Backend Developer", "Software Engineer"],
        "skills": ["Python", "Django", "REST API", "Git"],
        "description": "Assesses backend development skills and understanding of software engineering principles."
    },
    {
        "name": "Frontend Development Assessment",
        "url": "https://shl.com/assessments/frontend-development-assessment",
        "remote_support": True,
        "adaptive": True,
        "duration": "45 mins",
        "test_type": "Skill-based",
        "roles": ["Frontend Developer", "UI Developer"],
        "skills": ["HTML", "CSS", "JavaScript", "React"],
        "description": "Evaluates a candidate's ability to create responsive and interactive user interfaces."
    },
    {
        "name": "Data Analysis Assessment",
        "url": "https://shl.com/assessments/data-analysis-assessment",
        "remote_support": True,
        "adaptive": False,
        "duration": "40 mins",
        "test_type": "Skill-based",
        "roles": ["Data Analyst", "Business Analyst"],
        "skills": ["Excel", "Python", "SQL", "Data Visualization"],
        "description": "Tests the ability to clean, analyze, and visualize data."
    },
    {
        "name": "Machine Learning Assessment",
        "url": "https://shl.com/assessments/machine-learning-assessment",
        "remote_support": True,
        "adaptive": False,
        "duration": "50 mins",
        "test_type": "Skill-based",
        "roles": ["Machine Learning Engineer", "Data Scientist"],
        "skills": ["Python", "Machine Learning", "Scikit-learn", "Model Evaluation"],
        "description": "Assesses knowledge of machine learning algorithms and practical implementation."
    },
    {
        "name": "DevOps Assessment",
        "url": "https://shl.com/assessments/devops-assessment",
        "remote_support": True,
        "adaptive": True,
        "duration": "60 mins",
        "test_type": "Skill-based",
        "roles": ["DevOps Engineer", "Cloud Engineer"],
        "skills": ["Docker", "Kubernetes", "CI/CD", "Linux"],
        "description": "Tests the understanding of modern DevOps practices and cloud infrastructure."
    },
    
  {
    "name": "Mobile App Developer Assessment",
    "url": "https://shl.com/assessments/mobile-developer",
    "remote_support": True,
    "adaptive": False,
    "duration": "50 mins",
    "test_type": "Technical",
    "roles": ["Mobile Developer", "Android Developer", "iOS Developer"],
    "skills": ["Kotlin", "Swift", "React Native", "Mobile UI/UX"],
    "description": "Evaluates mobile development knowledge across platforms and user experience understanding."
  },
  {
    "name": "Quality Assurance Engineer Assessment",
    "url": "https://shl.com/assessments/qa-engineer",
    "remote_support": True,
    "adaptive": True,
    "duration": "40 mins",
    "test_type": "Skill-based",
    "roles": ["QA Engineer", "Test Engineer"],
    "skills": ["Manual Testing", "Automation", "Selenium", "Bug Tracking"],
    "description": "Tests ability to design, execute, and report tests for software applications."
  },
  {
    "name": "AI/ML Engineer Assessment",
    "url": "https://shl.com/assessments/ai-ml-engineer",
    "remote_support": True,
    "adaptive": True,
    "duration": "75 mins",
    "test_type": "Advanced Technical",
    "roles": ["AI Engineer", "ML Engineer", "Data Scientist"],
    "skills": ["Python", "TensorFlow", "NLP", "Model Training"],
    "description": "Assesses proficiency in building machine learning models and understanding AI frameworks."
  },
  {
    "name": "Product Manager Assessment",
    "url": "https://shl.com/assessments/product-manager",
    "remote_support": False,
    "adaptive": False,
    "duration": "60 mins",
    "test_type": "Behavioral + Analytical",
    "roles": ["Product Manager", "Product Owner"],
    "skills": ["Market Analysis", "Feature Prioritization", "Agile", "Communication"],
    "description": "Evaluates leadership, product thinking, and stakeholder communication skills."
  },
  {
    "name": "Database Developer Assessment",
    "url": "https://shl.com/assessments/database-developer",
    "remote_support": True,
    "adaptive": True,
    "duration": "50 mins",
    "test_type": "Technical",
    "roles": ["Database Developer", "SQL Developer"],
    "skills": ["SQL", "Stored Procedures", "Data Modeling", "Indexing"],
    "description": "Tests understanding of database design, queries, and performance optimization."
  },
  {
    "name": "Technical Support Engineer Assessment",
    "url": "https://shl.com/assessments/tech-support",
    "remote_support": True,
    "adaptive": False,
    "duration": "40 mins",
    "test_type": "Customer-Facing Technical",
    "roles": ["Support Engineer", "Help Desk Technician"],
    "skills": ["Troubleshooting", "Networking", "Ticketing Tools", "Customer Service"],
    "description": "Evaluates communication and diagnostic skills for resolving technical issues."
  },
  {
    "name": "UI/UX Designer Assessment",
    "url": "https://shl.com/assessments/ui-ux",
    "remote_support": False,
    "adaptive": True,
    "duration": "45 mins",
    "test_type": "Design Aptitude",
    "roles": ["UI Designer", "UX Designer"],
    "skills": ["Wireframing", "User Research", "Figma", "Accessibility"],
    "description": "Assesses ability to create intuitive and aesthetically pleasing user experiences."
  },
  {
    "name": "Cloud Architect Assessment",
    "url": "https://shl.com/assessments/cloud-architect",
    "remote_support": True,
    "adaptive": False,
    "duration": "70 mins",
    "test_type": "Architecture + Design",
    "roles": ["Cloud Architect", "Infrastructure Engineer"],
    "skills": ["AWS", "Azure", "Architecture Design", "Cost Optimization"],
    "description": "Tests the ability to design scalable, secure, and cost-effective cloud infrastructure."
  },
  {
    "name": "Business Analyst Assessment",
    "url": "https://shl.com/assessments/business-analyst",
    "remote_support": True,
    "adaptive": False,
    "duration": "50 mins",
    "test_type": "Analytical",
    "roles": ["Business Analyst", "Operations Analyst"],
    "skills": ["Requirement Gathering", "Data Analysis", "Stakeholder Management", "Flowcharts"],
    "description": "Measures business analysis skills, logical thinking, and communication clarity."
  },
  {
    "name": "Technical Writing Assessment",
    "url": "https://shl.com/assessments/technical-writer",
    "remote_support": True,
    "adaptive": False,
    "duration": "40 mins",
    "test_type": "Language + Technical",
    "roles": ["Technical Writer", "Documentation Specialist"],
    "skills": ["Writing", "Technical Documentation", "Clarity", "Structure"],
    "description": "Assesses ability to produce clear and accurate documentation for technical audiences."
  },
  
  {
    "name": "Cybersecurity Analyst Assessment",
    "url": "https://shl.com/assessments/cybersecurity-analyst",
    "remote_support": True,
    "adaptive": True,
    "duration": "60 mins",
    "test_type": "Technical",
    "roles": ["Cybersecurity Analyst", "Security Engineer"],
    "skills": ["Network Security", "Risk Assessment", "Threat Detection", "Incident Response"],
    "description": "Evaluates knowledge of cybersecurity protocols, threat mitigation, and security frameworks."
  },
  {
    "name": "Data Analyst Assessment",
    "url": "https://shl.com/assessments/data-analyst",
    "remote_support": True,
    "adaptive": False,
    "duration": "50 mins",
    "test_type": "Analytical",
    "roles": ["Data Analyst", "BI Analyst"],
    "skills": ["Excel", "SQL", "Data Visualization", "Statistics"],
    "description": "Tests data interpretation, visualization, and basic statistical analysis."
  },
  {
    "name": "Full Stack Developer Assessment",
    "url": "https://shl.com/assessments/full-stack",
    "remote_support": True,
    "adaptive": True,
    "duration": "90 mins",
    "test_type": "Technical",
    "roles": ["Full Stack Developer", "Web Developer"],
    "skills": ["React", "Node.js", "MongoDB", "REST APIs"],
    "description": "Covers front-end and back-end technologies used in building full stack applications."
  },
  {
    "name": "Digital Marketing Assessment",
    "url": "https://shl.com/assessments/digital-marketing",
    "remote_support": True,
    "adaptive": False,
    "duration": "45 mins",
    "test_type": "Marketing",
    "roles": ["Digital Marketer", "SEO Specialist"],
    "skills": ["SEO", "Google Ads", "Social Media Marketing", "Analytics"],
    "description": "Measures digital campaign planning, SEO/SEM, and analytical skills."
  },
  {
    "name": "Graphic Designer Assessment",
    "url": "https://shl.com/assessments/graphic-designer",
    "remote_support": False,
    "adaptive": False,
    "duration": "40 mins",
    "test_type": "Creative",
    "roles": ["Graphic Designer", "Visual Designer"],
    "skills": ["Adobe Photoshop", "Illustrator", "Color Theory", "Typography"],
    "description": "Tests visual creativity, design principles, and tool proficiency."
  },
  {
    "name": "Network Engineer Assessment",
    "url": "https://shl.com/assessments/network-engineer",
    "remote_support": True,
    "adaptive": True,
    "duration": "60 mins",
    "test_type": "Infrastructure",
    "roles": ["Network Engineer", "System Administrator"],
    "skills": ["Routing", "Switching", "Firewalls", "Network Protocols"],
    "description": "Covers foundational and advanced networking concepts and troubleshooting."
  },
  {
    "name": "Sales Executive Assessment",
    "url": "https://shl.com/assessments/sales-executive",
    "remote_support": False,
    "adaptive": False,
    "duration": "35 mins",
    "test_type": "Behavioral + Sales Aptitude",
    "roles": ["Sales Executive", "Business Development Representative"],
    "skills": ["Persuasion", "Lead Generation", "CRM", "Negotiation"],
    "description": "Evaluates ability to build client relationships and close deals effectively."
  },
  {
    "name": "Project Manager Assessment",
    "url": "https://shl.com/assessments/project-manager",
    "remote_support": True,
    "adaptive": False,
    "duration": "60 mins",
    "test_type": "Management",
    "roles": ["Project Manager", "Scrum Master"],
    "skills": ["Agile", "Risk Management", "Gantt Charts", "Stakeholder Management"],
    "description": "Tests leadership and organizational skills for managing cross-functional teams and timelines."
  },
  {
    "name": "Frontend Developer Assessment",
    "url": "https://shl.com/assessments/frontend-developer",
    "remote_support": True,
    "adaptive": True,
    "duration": "60 mins",
    "test_type": "Technical",
    "roles": ["Frontend Developer", "UI Engineer"],
    "skills": ["HTML", "CSS", "JavaScript", "React"],
    "description": "Evaluates ability to build responsive and accessible web interfaces."
  },
  {
    "name": "IT Support Technician Assessment",
    "url": "https://shl.com/assessments/it-support",
    "remote_support": True,
    "adaptive": False,
    "duration": "40 mins",
    "test_type": "Technical Support",
    "roles": ["IT Support", "Desktop Technician"],
    "skills": ["Windows Troubleshooting", "Hardware Basics", "Software Installation", "Helpdesk Tools"],
    "description": "Measures skills in resolving technical support tickets and customer queries efficiently."
  },
  
  {
    "name": "Backend Developer Assessment",
    "url": "https://shl.com/assessments/backend-developer",
    "remote_support": True,
    "adaptive": True,
    "duration": "75 mins",
    "test_type": "Technical",
    "roles": ["Backend Developer", "Software Engineer"],
    "skills": ["Java", "Spring Boot", "REST APIs", "Database Design"],
    "description": "Evaluates server-side logic, API integration, and database handling."
  },
  {
    "name": "AI/ML Engineer Assessment",
    "url": "https://shl.com/assessments/ai-ml-engineer",
    "remote_support": True,
    "adaptive": True,
    "duration": "90 mins",
    "test_type": "Technical",
    "roles": ["Machine Learning Engineer", "AI Developer"],
    "skills": ["Python", "TensorFlow", "Scikit-Learn", "Model Evaluation"],
    "description": "Covers machine learning algorithms, model tuning, and data preparation."
  },
  {
    "name": "HR Manager Assessment",
    "url": "https://shl.com/assessments/hr-manager",
    "remote_support": False,
    "adaptive": False,
    "duration": "45 mins",
    "test_type": "Managerial",
    "roles": ["HR Manager", "Talent Acquisition Lead"],
    "skills": ["Recruitment", "Policy Making", "Conflict Resolution", "Onboarding"],
    "description": "Measures HR policy knowledge, employee engagement, and conflict handling."
  },
  {
    "name": "Quality Assurance Assessment",
    "url": "https://shl.com/assessments/qa-assessment",
    "remote_support": True,
    "adaptive": False,
    "duration": "60 mins",
    "test_type": "Technical",
    "roles": ["QA Engineer", "Software Tester"],
    "skills": ["Selenium", "Test Cases", "Bug Tracking", "Automation"],
    "description": "Tests software testing methodologies, tools, and automation skills."
  },
  {
    "name": "Cloud Architect Assessment",
    "url": "https://shl.com/assessments/cloud-architect",
    "remote_support": True,
    "adaptive": True,
    "duration": "75 mins",
    "test_type": "Technical",
    "roles": ["Cloud Architect", "Infrastructure Engineer"],
    "skills": ["AWS", "Azure", "Cloud Security", "Solution Design"],
    "description": "Assesses ability to design secure and scalable cloud architectures."
  },
  {
    "name": "Mobile App Developer Assessment",
    "url": "https://shl.com/assessments/mobile-developer",
    "remote_support": True,
    "adaptive": False,
    "duration": "60 mins",
    "test_type": "Technical",
    "roles": ["Mobile Developer", "iOS/Android Engineer"],
    "skills": ["Kotlin", "Swift", "React Native", "Mobile UI"],
    "description": "Evaluates mobile app development, performance optimization, and user experience."
  },
  {
    "name": "Content Writer Assessment",
    "url": "https://shl.com/assessments/content-writer",
    "remote_support": False,
    "adaptive": False,
    "duration": "40 mins",
    "test_type": "Creative",
    "roles": ["Content Writer", "Copywriter"],
    "skills": ["Grammar", "SEO Writing", "Tone", "Research"],
    "description": "Tests creative writing, readability, and ability to write for digital platforms."
  },
  {
    "name": "Database Administrator Assessment",
    "url": "https://shl.com/assessments/database-admin",
    "remote_support": True,
    "adaptive": False,
    "duration": "60 mins",
    "test_type": "Technical",
    "roles": ["DBA", "Data Engineer"],
    "skills": ["SQL", "Indexing", "Backup & Recovery", "Database Security"],
    "description": "Evaluates knowledge of database management, optimization, and troubleshooting."
  },
  {
    "name": "Business Analyst Assessment",
    "url": "https://shl.com/assessments/business-analyst",
    "remote_support": True,
    "adaptive": False,
    "duration": "50 mins",
    "test_type": "Analytical",
    "roles": ["Business Analyst", "Product Analyst"],
    "skills": ["Requirement Gathering", "Documentation", "UML", "Stakeholder Communication"],
    "description": "Covers analysis techniques, stakeholder management, and documentation standards."
  },
  {
    "name": "Technical Support Engineer Assessment",
    "url": "https://shl.com/assessments/technical-support",
    "remote_support": True,
    "adaptive": False,
    "duration": "45 mins",
    "test_type": "Technical Support",
    "roles": ["Support Engineer", "Helpdesk Executive"],
    "skills": ["Troubleshooting", "Ticketing Systems", "Customer Support", "Networking Basics"],
    "description": "Measures ability to handle technical queries and resolve issues efficiently."
  },
  {
    "name": "Frontend Developer Assessment",
    "url": "https://shl.com/assessments/frontend-developer",
    "remote_support": True,
    "adaptive": True,
    "duration": "60 mins",
    "test_type": "Technical",
    "roles": ["Frontend Developer", "UI Developer"],
    "skills": ["HTML", "CSS", "JavaScript", "React"],
    "description": "Assesses UI development, responsive design, and JavaScript frameworks."
  },
  {
    "name": "Cybersecurity Assessment",
    "url": "https://shl.com/assessments/cybersecurity-assessment",
    "remote_support": True,
    "adaptive": False,
    "duration": "70 mins",
    "test_type": "Technical",
    "roles": ["Cybersecurity Analyst", "Security Engineer"],
    "skills": ["Vulnerability Management", "Network Security", "SIEM", "Firewalls"],
    "description": "Evaluates knowledge of securing infrastructure and identifying threats."
  },
  {
    "name": "Product Manager Assessment",
    "url": "https://shl.com/assessments/product-manager",
    "remote_support": False,
    "adaptive": False,
    "duration": "55 mins",
    "test_type": "Managerial",
    "roles": ["Product Manager", "Product Owner"],
    "skills": ["Roadmapping", "Agile", "Prioritization", "Stakeholder Communication"],
    "description": "Measures planning, product thinking, and leadership skills."
  },
  {
    "name": "UI/UX Designer Assessment",
    "url": "https://shl.com/assessments/ui-ux-designer",
    "remote_support": True,
    "adaptive": False,
    "duration": "50 mins",
    "test_type": "Creative",
    "roles": ["UI Designer", "UX Designer"],
    "skills": ["Wireframing", "Prototyping", "Figma", "User Research"],
    "description": "Evaluates understanding of user-centered design and prototyping tools."
  },
  {
    "name": "Data Analyst Assessment",
    "url": "https://shl.com/assessments/data-analyst",
    "remote_support": True,
    "adaptive": True,
    "duration": "65 mins",
    "test_type": "Analytical",
    "roles": ["Data Analyst", "BI Analyst"],
    "skills": ["SQL", "Excel", "Data Visualization", "Statistics"],
    "description": "Tests ability to interpret data, run queries, and build dashboards."
  },
  {
    "name": "Python Developer Assessment",
    "url": "https://shl.com/assessments/python-developer",
    "remote_support": True,
    "adaptive": True,
    "duration": "70 mins",
    "test_type": "Technical",
    "roles": ["Python Developer", "Software Engineer"],
    "skills": ["OOP", "Pandas", "Flask", "Problem Solving"],
    "description": "Covers Python coding, frameworks, and algorithmic thinking."
  },
  {
    "name": "Java Developer Assessment",
    "url": "https://shl.com/assessments/java-developer",
    "remote_support": True,
    "adaptive": False,
    "duration": "75 mins",
    "test_type": "Technical",
    "roles": ["Java Developer", "Backend Engineer"],
    "skills": ["Java", "OOP", "Collections", "Multithreading"],
    "description": "Tests Java core concepts and backend programming skills."
  },
  {
    "name": "Project Manager Assessment",
    "url": "https://shl.com/assessments/project-manager",
    "remote_support": False,
    "adaptive": False,
    "duration": "60 mins",
    "test_type": "Managerial",
    "roles": ["Project Manager", "Delivery Manager"],
    "skills": ["Project Planning", "Budgeting", "Risk Management", "Scrum"],
    "description": "Assesses leadership in project execution and stakeholder coordination."
  },
  {
    "name": "Sales Executive Assessment",
    "url": "https://shl.com/assessments/sales-executive",
    "remote_support": False,
    "adaptive": False,
    "duration": "45 mins",
    "test_type": "Sales",
    "roles": ["Sales Executive", "Business Development Associate"],
    "skills": ["Lead Generation", "CRM", "Negotiation", "Pitching"],
    "description": "Measures persuasion, communication, and deal-closing abilities."
  },
  {
    "name": "Digital Marketing Assessment",
    "url": "https://shl.com/assessments/digital-marketing",
    "remote_support": True,
    "adaptive": False,
    "duration": "60 mins",
    "test_type": "Marketing",
    "roles": ["Digital Marketer", "SEO Specialist"],
    "skills": ["SEO", "Google Ads", "Analytics", "Content Marketing"],
    "description": "Tests understanding of marketing channels, analytics, and optimization."
  },
  {
    "name": "Finance Analyst Assessment",
    "url": "https://shl.com/assessments/finance-analyst",
    "remote_support": True,
    "adaptive": False,
    "duration": "65 mins",
    "test_type": "Analytical",
    "roles": ["Finance Analyst", "Investment Analyst"],
    "skills": ["Financial Modelling", "Valuation", "Excel", "Reporting"],
    "description": "Covers corporate finance, forecasting, and ratio analysis."
  },
  {
    "name": "Network Engineer Assessment",
    "url": "https://shl.com/assessments/network-engineer",
    "remote_support": True,
    "adaptive": False,
    "duration": "70 mins",
    "test_type": "Technical",
    "roles": ["Network Engineer", "Infrastructure Engineer"],
    "skills": ["TCP/IP", "Routing", "Switching", "Firewall Configuration"],
    "description": "Assesses knowledge of network setup, maintenance, and troubleshooting."
  },
  {
    "name": "Operations Manager Assessment",
    "url": "https://shl.com/assessments/operations-manager",
    "remote_support": False,
    "adaptive": False,
    "duration": "55 mins",
    "test_type": "Managerial",
    "roles": ["Operations Manager", "Supply Chain Lead"],
    "skills": ["Logistics", "Process Optimization", "Inventory Control", "Cost Management"],
    "description": "Evaluates skills in operations planning, control, and logistics management."
  },
  {
    "name": "Game Developer Assessment",
    "url": "https://shl.com/assessments/game-developer",
    "remote_support": True,
    "adaptive": False,
    "duration": "60 mins",
    "test_type": "Technical",
    "roles": ["Game Developer", "Unity Developer"],
    "skills": ["Unity", "C#", "Game Design", "Animation"],
    "description": "Tests proficiency in game development engines and physics programming."
  },
  {
    "name": "Legal Advisor Assessment",
    "url": "https://shl.com/assessments/legal-advisor",
    "remote_support": False,
    "adaptive": False,
    "duration": "50 mins",
    "test_type": "Legal",
    "roles": ["Legal Advisor", "Compliance Officer"],
    "skills": ["Legal Drafting", "Contract Law", "Regulatory Compliance", "Litigation"],
    "description": "Evaluates understanding of legal frameworks and corporate regulations."
  },
  {
    "name": "Customer Service Assessment",
    "url": "https://shl.com/assessments/customer-service",
    "remote_support": False,
    "adaptive": False,
    "duration": "40 mins",
    "test_type": "Support",
    "roles": ["Customer Service Executive", "Support Agent"],
    "skills": ["Communication", "Problem Solving", "Empathy", "CRM Systems"],
    "description": "Assesses handling of customer queries and service quality."
  },
  {
    "name": "Embedded Systems Engineer Assessment",
    "url": "https://shl.com/assessments/embedded-engineer",
    "remote_support": True,
    "adaptive": False,
    "duration": "80 mins",
    "test_type": "Technical",
    "roles": ["Embedded Systems Engineer"],
    "skills": ["C", "Microcontrollers", "RTOS", "UART"],
    "description": "Tests low-level programming, memory management, and hardware interfaces."
  },
  {
    "name": "Blockchain Developer Assessment",
    "url": "https://shl.com/assessments/blockchain-developer",
    "remote_support": True,
    "adaptive": True,
    "duration": "75 mins",
    "test_type": "Technical",
    "roles": ["Blockchain Developer"],
    "skills": ["Solidity", "Smart Contracts", "Ethereum", "Cryptography"],
    "description": "Assesses ability to build decentralized apps and smart contracts."
  },
  {
    "name": "Graphic Designer Assessment",
    "url": "https://shl.com/assessments/graphic-designer",
    "remote_support": False,
    "adaptive": False,
    "duration": "45 mins",
    "test_type": "Creative",
    "roles": ["Graphic Designer", "Visual Designer"],
    "skills": ["Photoshop", "Illustrator", "Typography", "Layout"],
    "description": "Measures creativity, attention to detail, and visual communication."
  },
  {
    "name": "Full Stack Developer Assessment",
    "url": "https://shl.com/assessments/fullstack-developer",
    "remote_support": True,
    "adaptive": True,
    "duration": "90 mins",
    "test_type": "Technical",
    "roles": ["Full Stack Developer"],
    "skills": ["JavaScript", "Node.js", "React", "MongoDB"],
    "description": "Covers backend, frontend, and API integration for full-stack projects."
  }
]


